export const Countries = {
  SEL: 'Select',
  AF: 'Afghanistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  IC: 'Canary Islands',
  CV: 'Cape Verde',
  BQ: 'Caribbean Netherlands (Bonaire)',
  BES: 'Caribbean Netherlands (Sint Eustatius and Saba)',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo, Republic of the',
  CD: 'Congo, the Democratic Republic of the',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: "Cote D'ivoire",
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curacao',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (Malvinas)',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island and Mcdonald Islands',
  VA: 'Holy See (Vatican City State)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran, Islamic Republic of',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: "Korea, Democratic People's Republic of",
  KR: 'Korea, Republic of',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  CH: 'Lake Lugano, Territorial Waters of',
  LA: "Lao People's Democratic Republic",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libyan Arab Jamahiriya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LVG: 'Livigno',
  LU: 'Luxembourg',
  MO: 'Macau',
  MK: 'Macedonia, the Former Yugoslav Republic of',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands (The)',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia (Federated States Of)',
  MD: 'Moldova, Republic of',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands (The)',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territory, Occupied',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn Islands',
  PL: 'Poland',
  PT: 'Portugal',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  BL: 'Saint Barthelemy',
  SH: 'Saint Helena',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  SLA: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SZ: 'Swaziland',
  SE: 'Sweden',
  SW: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania, United Republic of',
  TH: 'Thailand',
  TL: 'Timor-leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  UNI: 'United Kingdom (Northern Ireland)',
  UM: 'United States Minor Outlying Islands (The)',
  USA: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Vietnam',
  VI: 'Virgin Islands (U.S.)',
  VG: 'Virgin Islands, British',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const USA_States = {
  ' ': 'Select',
  AL: 'Alabama',
  AK: 'Alaska',
  AS: 'American Samoa',
  AZ: 'Arizona',
  AR: 'Arkansas',
  AE: 'Armed Forces Europe',
  AP: 'Armed Forces Pacific',
  AA: 'Armed Forces the Americas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  MP: 'Northern Mariana Islands',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UM: 'United States Minor Outlying Islands',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export const DocumentType = {
  sales_invoice: 'Sales Invoice',
  purchase_invoice: 'Purchase Invoice',
  return_invoice: 'Return Invoice',
  inventory_transfer_invoice: 'Inventory Transfer Invoice',
  inventory_transfer_outbound_invoice: 'Inventory Transfer Outbound Invoice',
  customs_invoice: 'Customs Invoice',
};

export const EntityUseCodes = {
  none: 'None',
  federal_government: 'A - Federal Government',
  state_government: 'B - State Government',
  tribal_government: 'C - Tribal Government',
  foreign_diplomat: 'D - Foreign Diplomat',
  charitable_exempt_organization: 'E - Charitable/Exempt Organization',
  religious_organization: 'F - Religious Organization',
  resale: 'G - Resale',
  agriculture: 'H - Agriculture',
  industrial_production_manufacturers: 'I - Industrial Prod/Manufacturers',
  direct_pay: 'J - Direct Pay',
  direct_mail: 'K - Direct Mail',
  educational_organization: 'M - Educational Organization',
  local_government: 'N - Local Government',
  commercial_aquaculture: 'P - Commercial Aquaculture',
  commercial_fishery: 'Q - Commercial Fishery',
  non_resident: 'R - Non-Resident',
  taxable_override_exemption: 'Taxable - Override Exemption',
  custom_entity_use_code: 'Use A Custom Entity/Use Code',
};

export const Attributes = {
  select: 'Select',
  address_classification: 'Address classification',
  age_group: 'Age group',
  age_of_vehicle: 'Age of vehicle',
  alcohol_content: 'Alcohol content',
  alcohol_route_type: 'Alcohol route type',
  alcohol_license_required: 'Alcohollicenserequired',
  alcohol_license_type: 'Alcohollicensetype',
  alcohol_threshold_limit: 'Alcoholthresholdlimit',
  alternative_fuel_percentage: 'Alternative fuel percentage',
  annual_production_volume: 'Annual production volume',
  annual_room_revenue: 'Annual room revenue',
  api_item_allocation: 'Apitemallocation',
  api_item_entity_use_code: 'Apitementityusecode',
  applicable_ap_post_actions: 'Applicable ap post actions',
  ap_top_down_distribution: 'Aptopdowndistribution',
  asin: 'Asin',
  availability: 'Availability',
  average_daily_rate: 'Average daily rate',
  base_room_rate: 'Base room rate',
  beverage_container_material: 'Beverage container material',
  beverage_container_type: 'Beverage container type',
  bill_to_dob: 'Bill to dob',
  boat_propulsion_type: 'Boat propulsion type',
  brand: 'Brand',
  calculate_beverage_alcohol_excise_tax:
    'Calculate beverage alcohol excise tax',
  carrier_code: 'Carrier code',
  catered: 'Catered',
  cellular_capability: 'Cellular capability',
  ciro_deminimis_exception: 'Ciro deminimis exception',
  color: 'Color',
  component: 'Component',
  condition: 'Condition',
  container_count: 'Container count',
  container_size: 'Container size',
  contains_mercury: 'Contains mercury',
  cost_center: 'Costcenter',
  country_of_manufacture: 'Country of manufacture',
  daily_rate: 'Daily rate',
  delivery_terms: 'Delivery terms',
  digital: 'Digital',
  discount_type: 'Discount type',
  disposable: 'Disposable',
  duty_deminimis_threshold: 'Dutydeminimisthreshold',
  ean: 'Ean',
  eating_facility_provisions: 'Eating facility provisions',
  electric_vehicle_charging_station_level:
    'Electric vehicle charging station level',
  establishment_type: 'Establishment type',
  event_space_size: 'Event space size',
  exempt_entity_performance: 'Exempt entity performance',
  exempt_status_approved: 'Exempt status approved',
  fda_warning: 'Fda warning',
  fee_type: 'Fee type',
  first_use: 'First use',
  food_preparation: 'Food preparation',
  food_and_beverage_sales: 'Foodandbeveragesales',
  fuel_economy: 'Fuel economy',
  fulfillment_house_code: 'Fulfillment house code',
  fullfillment_house_code: 'Fullfillment house code',
  gender: 'Gender',
  google_product_category: 'Google product category',
  gross_weight: 'Gross weight',
  gtin: 'Gtin',
  height: 'Height',
  home_consumption: 'Home consumption',
  hotel_owned_restaurant_on_site: 'Hotelownedrestaurantonsite',
  hs_hint: 'Hs hint',
  image_link: 'Image link',
  indigent_purchaser: 'Indigentpurchaser',
  in_state_pro_team: 'Instate pro team',
  insured: 'Insured',
  ioss_reg_no: 'Iossregno',
  is_accelerated_tax_paid: 'Is accelerated tax paid',
  is_alcohol_sample: 'Is alcohol sample',
  is_assembly_or_installation: 'Is assembly or installation',
  is_buyers_agent: 'Is buyers agent',
  is_certified_extended_stay: 'Is certified extended stay',
  is_colorado_smm_registered: 'Is colorado smm registered',
  is_customer_established: 'Is customer established',
  is_customer_registered_through_fiscal_rep:
    'Is customer registeredthrough fiscalrep',
  is_direct_alcohol_import: 'Is direct alcohol import',
  is_electric_vehicle: 'Is electric vehicle',
  is_entire_house_rented: 'Is entire house rented',
  is_eu_digital_service_thresh_exceeded:
    'Is eu digital service thresh exceeded',
  is_eu_distance_sales_threshold_exceeded:
    'Is eu distance sales threshold exceeded',
  is_eu_goods_document_total_below_150_eur:
    'Is eu goods document total below 150 eur',
  is_foreign_alcohol: 'Is foreign alcohol',
  is_goods_second_hand: 'Is goods second hand',
  is_heavy_machinery: 'Is heavy machinery',
  is_import_vat_deferment: 'Is import vat deferment',
  is_incidental_to_owner_use: 'Is incidental to owner use',
  is_indeterminate_length: 'Is indeterminate length',
  is_intercompany: 'Is intercompany',
  is_intermediary_appointed: 'Is intermediary appointed',
  is_luxury_vehicle: 'Is luxury vehicle',
  is_marketplace: 'Is marketplace',
  is_operator_provided: 'Is operator provided',
  is_owners_primary_address: "Is owner's primary address",
  is_preferred_program: 'Is preferred program',
  is_registered_solar_dealer: 'Is registered solar dealer',
  is_registered_through_fiscal_rep: 'Is registered through fiscal rep',
  is_registered_used_vehicle_dealer: 'Is registered used vehicle dealer',
  is_reseller: 'Is reseller',
  is_residence_owner_present: 'Is residence owner present',
  is_service_contract: 'Is service contract',
  is_short_term: 'Is short term',
  is_special_arrangement_by_carrier: 'Is special arrangement by carrier',
  is_start_up: 'Is start up',
  is_supplier_established: 'Is supplier established',
  is_taxable_service: 'Is taxable service',
  is_tax_included_exclude_multi_tax: 'Is taxincluded exclude multitax',
  is_temporary_import_18_months: 'Is temporary import 18 months',
  is_temporary_import_2_years: 'Is temporary import 2 years',
  is_texas_terp_eligible: 'Is texas terp eligible',
  is_triangulation: 'Is triangulation',
  is_used_vehicle: 'Is used vehicle',
  is_ap_batch_transaction: 'Isapbatchtransaction',
  is_below_rdf_threshold: 'Isbelowrdfthreshold',
  is_billed_to_principal: 'Isbilledtoprincipal',
  is_manual_allocation: 'Ismanualallocation',
  is_merchant_seller_tax_dependency: 'Ismerchantsellertaxdependency',
  is_permanent_establishment_responsible: 'Ispermanentestablishmentresponsible',
  is_registered_maquiladora: 'Isregisteredmaquiladora',
  is_registered_northern_border_region: 'Isregisterednortherborderregion',
  is_registered_northern_border_region2: 'Isregisterednorthernborderregion',
  is_registered_southern_border_region: 'Isregisteredsouthernborderregion',
  is_temporary_import: 'Istemporaryimport',
  item_grade: 'Item grade',
  kvic_approved: 'Kvic approved',
  license_jurisdiction: 'License jurisdiction',
  link: 'Link',
  listing_marketplace: 'Listingmarketplace',
  lodging_marketplace: 'Lodging marketplace',
  maintains_inventory: 'Maintains inventory',
  manufacturer_rebate_type: 'Manufacturer rebate type',
  market_place_type: 'Market place type',
  material: 'Material',
  merchant_establishment_country: 'Merchant establishment country',
  merchant_name: 'Merchantname',
  merchant_vat_id: 'Merchantvatid',
  middleman_vat_id: 'Middleman vatid',
  min_age: 'Minage',
  mode_of_transport: 'Modeoftransport',
  motor_horsepower: 'Motor horsepower',
  motor_type: 'Motor type',
  mpn: 'Mpn',
  nebraska_contractor_option: 'Nebraska contractor option',
  net_length: 'Net length',
  net_surface_area: 'Net surface area',
  net_volume: 'Net volume',
  net_weight: 'Net weight',
  number_of_days: 'Number of days',
  number_of_nights: 'Number of nights',
  number_of_rooms_in_unit: 'Number of rooms in unit',
  number_of_units_for_rent: 'Number of units for rent',
  overrides_parent_jurisdiction: 'Overridesparentjurisdiction',
  pack_size: 'Pack size',
  party_a_vat_id_country: 'Party a vatid country',
  party_c_vat_id_country: 'Party c vat id country',
  performance_type: 'Performancetype',
  pick_up_option: 'Pick up option',
  place_of_consumption: 'Place of consumption',
  policy_expiration: 'Policy expiration',
  policy_renewal: 'Policy renewal',
  policy_start: 'Policy start',
  primary_buyer: 'Primary buyer',
  primary_buyer_email: 'Primary buyer email',
  primary_buyer_first_name: 'Primary buyer first name',
  primary_buyer_last_name: 'Primary buyer last name',
  purchase_category: 'Purchase category',
  quality_grade: 'Quality grade',
  quantity: 'Quantity',
  recycle_rebate_category: 'Recycle rebate category',
  region: 'Region',
  resale_cert_required: 'Resale cert required',
  responsible_party: 'Responsible party',
  room_category: 'Room category',
  room_count: 'Room count',
  room_type: 'Room type',
  sale_status: 'Sale status',
  sale_type: 'Sale type',
  savings_rate: 'Savings rate',
  shipping_criteria: 'Shipping criteria',
  shipping_terms: 'Shipping terms',
  tax_rate: 'Tax rate',
  tax_schedule: 'Tax schedule',
  time_of_service: 'Time of service',
  transit_country: 'Transit country',
  transit_location_type: 'Transit location type',
  transportation_cost: 'Transportation cost',
  unit_type: 'Unit type',
  use_description: 'Use description',
  value: 'Value',
  vat_id: 'Vat id',
  weight: 'Weight',
  width: 'Width',
  work_with_imported_items: 'Work with imported items',
  zone_code: 'Zone code',
};

export const OverrideType = {
  exemption: 'Exemption',
  tax_amount: 'Tax Amount',
  tax_date: 'Tax Date',
};

export const Currencies = {
  select: 'Select',
  argentine_peso: 'Argentine Peso',
  australian_dollar: 'Australian Dollar',
  brazilian_real: 'Brazilian Real',
  british_pound_sterling: 'British Pound Sterling',
  canadian_dollar: 'Canadian Dollar',
  chinese_yuan_renminbi: 'Chinese Yuan Renminbi',
  egyptian_pound: 'Egyptian Pound',
  euro: 'Euro (European Union)',
  hong_kong_dollar: 'Hong Kong Dollar',
  indian_rupee: 'Indian Rupee',
  indonesian_rupiah: 'Indonesian Rupiah',
  japanese_yen: 'Japanese Yen',
  malaysian_ringgit: 'Malaysian Ringgit',
  mexican_peso: 'Mexican Peso',
  new_zealand_dollar: 'New Zealand Dollar',
  norwegian_krone: 'Norwegian Krone',
  pakistani_rupee: 'Pakistani Rupee',
  polish_zloty: 'Polish Zloty',
  russian_ruble: 'Russian Ruble',
  saudi_riyal: 'Saudi Riyal',
  singapore_dollar: 'Singapore Dollar',
  south_african_rand: 'South African Rand',
  south_korean_won: 'South Korean Won',
  swedish_krona: 'Swedish Krona',
  swiss_franc: 'Swiss Franc',
  thai_baht: 'Thai Baht',
  turkish_lira: 'Turkish Lira',
  uae_dirham: 'United Arab Emirates Dirham',
  us_dollar: 'United States Dollar',
  vietnamese_dong: 'Vietnamese Dong',
};

// // Select the <select> element by its ID
// const selectElement = document.getElementById('ember22560');

// // Check if the element exists
// if (selectElement) {
//   // Select all <option> elements within the <select>
//   const options = selectElement.querySelectorAll('option');

//   // Traverse each <option> and log its text value
//   const values = Array.from(options).map((option) => option.textContent.trim());
//   console.log(values);
// } else {
//   console.log('Element with ID ember22560 not found');
// }
